### ISSUE TITLE
xcode-archive: force_team_id and team_id seem broken 

### ISSUE THREAD

**Issue by wrasmuss-eng** [bitrise-io/bitrise-steplib#1106]
We're using legacy code signing. We have not gotten around to switching to automatic yet.

We had a situation where a developer set the development team value to a different team and xcode-archive code signing started failing

I tried using the force_team_id and team_id options but I got error code 65 and in one case error code 64.

I switched to using this xcodebuild_options: -DEVELOPMENT_TEAM=<our id here> and everything works fine.

**Comment by viktorbenei** [comment]
Hi,

Thanks for sharing this @wrasmuss-eng !

That said, could you please share this in the step's github repo? https://github.com/bitrise-io/steps-xcode-archive

This is the StepLib's repo & tracker, only StepLib related issues should be reported here.
