### ISSUE TITLE
Can't finish share-this-step command

### ISSUE THREAD

**Issue by munirwanis** [bitrise-io/bitrise-steplib#1239]
When I run `bitrise run share-this-step` it returns an error of forbidden access to push. Am I doing something wrong?

![screen shot 2017-10-31 at 01 34 57](https://user-images.githubusercontent.com/8562684/32206371-c24f76a4-bddb-11e7-87da-71646fd4c556.png)

**Comment by trapacska** [comment]
Hey @munirwanis !

If I see correctly, you have our steplib repository as "your own fork" which is incorrect. Please fork our steplib (https://github.com/bitrise-io/bitrise-steplib) and set that repository as your own.


Closing the issue now, as it doesn't seems like to be an issue with Bitrise CLI or Steplib.

If you still encounter any issue, please contact us on our on-site chat!

**Comment by munirwanis** [comment]
Oh, now I get it! I'll fix this. Thank you!
