### ISSUE TITLE
Android projects using Gradle's Kotlin DSL will not build.

### ISSUE THREAD

**Issue by es0329** [bitrise-io/bitrise-steplib#1918]
I've created a sample project, [miniature-succotash-0.0.1.zip](https://github.com/bitrise-io/bitrise-steplib/files/2920072/miniature-succotash-0.0.1.zip), to demonstrate Bitrise's build step doesn't recognize `build.gradle.kts`. See failing build/logs [here](https://app.bitrise.io/build/4eabe0951dcd1f1a).

This example shows a simple packaging. Like the Groovy DSL, projects may include Kotlin files in `project/buildSrc/com/kotlin/build.gradle.kts`.

cc @viktorbenei

**Comment by fehersanyi-bitrise** [comment]
Hello there!

the kotlin scanner is in this current sprint, so the full support for it will be available in the following weeks 🙃

**Comment by ofalvai** [comment]
I'm closing this old issue as Kotlin DSL support has been added, we just forgot to update this issue.
