### ISSUE TITLE
[abandoned step] bitrise-android-application-attributes-step

### ISSUE THREAD

**Issue by EMarshal** [bitrise-io/bitrise-steplib#1943]
There's been an issue in this step with parsing application names for a couple years at heyjobs/bitrise-android-application-attributes-step#1 that I created a PR for at heyjobs/bitrise-android-application-attributes-step#2 that hasn't received any attention in that timespan.

**Comment by fehersanyi-bitrise** [comment]
Hello there, as you see this step is "abandoned" thus we do not update it any more, also I checked your PR about unity, we plan to release full support for unity projects this summer, or early fall (if everything goes as planned)

**Comment by EMarshal** [comment]
> Hello there, as you see this step is "abandoned" thus we do not update it any more

What does this mean? Am I missing some way to get equivalent functionality in Bitrise? Is there any way to get the step forked to bitrise-community so that fixes can get merged?

> I checked your PR about unity

I think someone else?

**Comment by bitce** [comment]
Hi @EMarshal,

Depending on what you are trying to do there are quite a few with similar functionalities:

<img width="622" alt="Screenshot 2019-03-20 at 15 48 33" src="https://user-images.githubusercontent.com/40164469/54693994-d91ee880-4b27-11e9-9997-523b4b1ed8b2.png">

But this step is indeed will not be maintained or updated in any shape or form in the future.

**Comment by EMarshal** [comment]
I was able to do what I wanted using https://github.com/jsauve/set-android-manifest-values.

Might be nice to have some indication of when/which steps are abandoned and no longer accepting any bug fixes.
