### ISSUE TITLE
certificate-and-profile-installer not allowing certificate password editing

### ISSUE THREAD

**Issue by igorfraa** [bitrise-io/bitrise-steplib#2014]
### Observed behaviour:
When adding a password for code signing certificate, it is impossible to edit password field before clicking on the eye icon to show the password.

Clicking on the icon second time disables the password field.

### Expected behaviour:
Password field is enabled all the time. Click on the eye icon shows/hides the password.

**Comment by bitce** [comment]
Hi @igorfraa!

Thanks for sharing your insight! This is completely intended, you indeed need to reveal the password first to edit it. I personally not sure why'd we'd want to change this behaviour, but if you'd like to see it changed you're more than welcome to submit a f[eature request](https://discuss.bitrise.io/c/feature-request) about it!

**Comment by igorfraa** [comment]
Hi @bitce 

Please ignore if this is intended
