### ISSUE TITLE
[abandoned step] bitrise-step-open-vpn

### ISSUE THREAD

**Issue by guness** [bitrise-io/bitrise-steplib#2184]
this step seems to be abandoned, everyone has own fork fixing some problems.
I have created an issue and got no response for 12 days. Maybe an official attempt would help.
https://github.com/justice3120/bitrise-step-open-vpn

I am happy to take over maintenance of the step or support it if Bitrise converts it to official step, unless owner disagrees.

**Comment by koral--** [comment]
Normally such step should be forked to bitrise-steplib org as community step: https://discuss.bitrise.io/t/bitrise-steps-community/496/28

**Comment by guness** [comment]
would you care to share the reason for closing @shams-ahmed ?

**Comment by shams-ahmed** [comment]
HI @guness, this ticket has been inactive for quite some time.

Please let us know if you're still experiencing an issue..

**Comment by guness** [comment]
Well, I don't experience this issue anymore, but it is not because this issue is fixed. It is basically because I changed my job twice since then.

New meta: **Change the job as a fix of an issue.**
