### ISSUE TITLE
[abandoned step] bitrise-step-browserstack-upload

### ISSUE THREAD

**Issue by guness** [bitrise-io/bitrise-steplib#2197]
this step seems to be abandoned
I have created two issues and a PR that fixes both however got no response for 6 days. Maybe an official attempt would help.
https://github.com/marcelkalveram/bitrise-step-browserstack-upload.git

**Comment by koral--** [comment]
I think it is too early to say that step is abandoned. I would give at least 3 weeks for response.

**Comment by guness** [comment]
> I think it is too early to say that step is abandoned. I would give at least 3 weeks for response.

Yeah I think I was a bit early on this. lets not mark this step abandoned a while, maybe maintainer would see messages and reviews PR. 👌🏻

**Comment by guness** [comment]
Closing this appeal as I got a response from maintainer. Hope will figure it out soon.
