### ISSUE TITLE
share-this-step command cannot be completed

### ISSUE THREAD

**Issue by kanari3** [bitrise-io/bitrise-steplib#2488]
I'm trying to update my step.
However, it fails with the following error.
`remote: Invalid username or password.`

How can I be successful?

## logs

```
$ bitrise run share-this-step
...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/kanari3/bitrise-steplib.git/'
```

I've also tried the following, although it may be an older method

```
$ bitrise share create --tag [step-version-tag] --git [step-git-uri].git --stepid [step-id]

Almost done! You should review your Step's step.yml file (the one added to the local StepLib),
and once you're happy with it call $ bitrise share finish
```

```
$ bitrise share finish

Submitting the changes...
pushing to your fork: https://github.com/kanari3/bitrise-steplib.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/kanari3/bitrise-steplib.git/'
2020/05/14 16:48:21 Bitrise share finish failed, error: exit status 1
```

## confirmed

- `ssh -T git@github.com` -> successfully
- git pull & push in local bitrise-steplib repo
- check `git config --list`
- bitrise version 1.41.2

Is there anything else I should be doing?

**Comment by koral--** [comment]
The steplib fork repo URL uses https:
`https://github.com/kanari3/bitrise-steplib.git/`
While it seems that you are trying to connect with ssh (and I guess that you may have setup ssh keys):
`ssh -T git@github.com`

You can try changing steplib fork repo URL (in bitrise.yml) from https to ssh.

**Comment by kanari3** [comment]
@koral-- 
thanks. I went from https to ssh and it passed!

```
diff --git a/bitrise.yml b/bitrise.yml
-  - MY_STEPLIB_REPO_FORK_GIT_URL: https://github.com/kanari3/bitrise-steplib.git
+  - MY_STEPLIB_REPO_FORK_GIT_URL: git@github.com:kanari3/bitrise-steplib.git
```
