### ISSUE TITLE
close-jira-tasks parse error: Invalid numeric literal at line 1, column 6

### ISSUE THREAD

**Issue by johannwerner** [bitrise-io/bitrise-steplib#2501]
Even though the step says its successful I'm getting this error in the step.

Query to be executed in Jira: {
  "jql": "project = OP AND status = 'Dev Done (Not in Build)'",
  "startAt": 0,
  "maxResults": 20,
  "fields": [
    "id"
  ],
  "fieldsByKeys": false
}
parse error: Invalid numeric literal at line 1, column 6         

These are the values I'm putting in the step 
Jira project name: OP
Jira project URL: https://companyname.atlassian.net
Jira API token: {CorrectAPIToken}
Initial status: Dev Done (Not in Build)
Initial status: IN REVIEW
Custom field to update version number: {Empty }
App version: {Empty}

**Comment by koral--** [comment]
This kind of issue should be reported to the step's issue tracker: https://github.com/orestesgaolin/bitrise-close-jira-tasks

Tracker here is for steplib itself, not for individual steps.

**Comment by pedrodimoura** [comment]
Same problem here...

**Comment by pedrodimoura** [comment]
Same error here...

**Comment by Roland-Bak** [comment]
Hey there @pedrodimoura!
Please visit the issue at [https://github.com/orestesgaolin/bitrise-close-jira-tasks/issues/1](https://github.com/orestesgaolin/bitrise-close-jira-tasks/issues/1), as it is a community created step 🙂
