### ISSUE TITLE
SonarQube warning deprecated Java version 

### ISSUE THREAD

**Issue by nicholausadi** [bitrise-io/bitrise-steplib#2624]
Hi everyone,

I use SonarScanner step and I receive this deprecate Java warning from Sonar.
Can someone please update the Java version?

<img width="514" alt="Screen Shot 2020-08-13 at 22 09 34" src="https://user-images.githubusercontent.com/16891202/90152430-01a92180-ddb2-11ea-9481-a2ad25d9f07b.png">

Thanks

**Comment by lpusok** [comment]
@nicholausadi ,
Hope you managed to solve this problem, issues in this repository are not handled as support requests. Check support.bitrise.io for more information.
Please refer here on how to select Java version: https://devcenter.bitrise.io/infrastructure/virtual-machines/#managing-java-versions.
