### ISSUE TITLE
Deploygate builds are not available to download after a week

### ISSUE THREAD

**Issue by SanjayMallur** [bitrise-io/bitrise-steplib#2777]
When we upload android builds to deploygate, the link to download the apk is expired after a week. This is happening because of the expiration time mentioned in the URL. Where we can change this time?

Example download link: https://d2fjxyapcfdbwq.cloudfront.net/binaries/Global/60170/3553_36f6f68e67fd951c20520fbbf0fb31/app-name-production-release-bitrise-signed.apk?Expires=1606306514&Signature=XXX&Key-Pair-Id=XXX

**Comment by Janos-vrancsik** [comment]
Hi @SanjayMallur 

As you reported the issue on the main repository of the Step Library, the Deploygate team was not notified about it. I already reached out to them, so I'm sure they'll do their best to help you shortly.

Hope it'll be resolved soon!

Best,
Janos
Partnership manager @ Bitrise

**Comment by jmatsu** [comment]
@Janos-vrancsik 
Thank you for sharing!

@SanjayMallur 
We'll be supporting you in https://github.com/DeployGate/upload-app-bitrise-step/issues/12
