### ISSUE TITLE
ios-auto-provision-appstoreconnect@0.1.5 fails

### ISSUE THREAD

**Issue by defigor** [bitrise-io/bitrise-steplib#2808]
We are using ios-auto-provision-appstoreconnect with automatically using the latest version for our ios builds to provision certificates and it was working fine with version 0.1.4.
However, on 9th of Dec the step got upgraded to 0.1.5 and it started to fail in our builds:
failed to check if profile is valid: project uses containers that are missing from the provisioning profile: [iCloud.$(CFBundleIdentifier)]

When we changed back to 0.1.4 the build got fixed.

Would it be possible to look into this issue? Thanks in advance.

**Comment by bitce** [comment]
Sorry to hear about the issue, thanks for the report!

Can you please send us a link two both versions of a build? When were you downgrade and it works, and one where it fails on the latest. Thanks in advance.

**Comment by defigor** [comment]
The links are below:
0.1.4 build: https://app.bitrise.io/build/89e41dcc635453e1
0.1.5 build: https://app.bitrise.io/build/ce6291330637fb53

I did also report it via bitrise support, so potentially someone is already looking.

**Comment by bitce** [comment]
That's correct, we've created a task and it's already in progress. Thanks for the details!

**Comment by bitce** [comment]
We released a new version  (0.1.6) of the step, fixing the bug: https://github.com/bitrise-steplib/steps-ios-auto-provision-appstoreconnect/releases/tag/0.1.6 Make sure to use the latest. Let us know if you have any questions!

**Comment by defigor** [comment]
We've upgraded to the last step and now it works again, thank you!
