### ISSUE TITLE
[abandoned-step] Mobile quality

### ISSUE THREAD

**Issue by imranMnts** [bitrise-io/bitrise-steplib#2869]
This [step](https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/mobile-quality) can be removed because we separated it into 3 steps (#2865 #2866 #2867) to keep steps as clear as possible because we plan to add some other steps to monitor the quality of the mobile applications.

Moreover, the setup should be easier and people will be able to add a step only if it's useful in their case (or requested by the client eg.)

**Comment by koral--** [comment]
Steps cannot be removed but they are deprecated.
@imranMnts you should create a PR like this: https://github.com/bitrise-io/bitrise-steplib/pull/1459/files

**Comment by imranMnts** [comment]
I will do it, thank you.
