### ISSUE TITLE
deploy-to-bitrise-io: Error when trying to download bundletool-all.jar

### ISSUE THREAD

**Issue by auf1r2** [bitrise-io/bitrise-steplib#3056]
**Step**
`deploy-to-bitrise-io`

**Enviroment**
id: deploy-to-bitrise-io
version: 1.13.2
collection: https://github.com/bitrise-io/bitrise-steplib.git
toolkit: go  

**Steps to reproduce**
Use `deploy-to-bitrise-io` as usual to deploy Android `*.aab` files to Bitrise.

**Error from build log**
```
Uploading aab file: /bitrise/deploy/****
- analyzing aab
- fetching info
Could not download file from: unable to download file from: https://github.com/google/bundletool/releases/download/0.13.4/bundletool-all-0.13.4.jar. Status code: 404
```

**Comment by ofalvai** [comment]
@auf1r2 does this error fail your build? Although this is logged as an error, the step uses a fallback URL to download bundletool successfully for me:

```
Uploading aab file: /bitrise/deploy/app-release.aab
- analyzing aab
- fetching info
Could not download file from: unable to download file from: https://github.com/google/bundletool/releases/download/0.13.4/bundletool-all-0.13.4.jar. Status code: 404
URL used to download file: https://github.com/google/bundletool/releases/download/0.13.4/bundletool-all.jar
$ java "-jar" "/tmp/tool569489321/bundletool-all.jar" "dump" "manifest" "--bundle" "/bitrise/deploy/app-release.aab"
```

The error should be logged as a warning instead, but the build should not fail because of this. Let us know if you experience a failed build.
