### ISSUE TITLE
Danger step is missing BitBucket Server inputs

### ISSUE THREAD

**Issue by alexanderwe** [bitrise-io/bitrise-steplib#3067]
I wanted to use the official danger step in my workflow to work with an on premise BitBucket Server instance. Unfortunately the step only offers input fields for GitHub or Gitlab. But Danger itself can work with BitBucket Server instances as it can be read here: https://danger.systems/js/usage/bitbucket_server.html

As a workaround I set the env vars in my workflow config and use the `Script` step to invoke danger. I know that this is a not a big issue, but it would be nice if the official Danger step could support input fields for all SCM systems that are supported by the Danger CLI.

**Comment by Roland-Bak** [comment]
Hello there @alexanderwe 👋

I forwarded your suggestion to the Product Team, but you can also raise a Feature Request on our forums here: https://discuss.bitrise.io/c/feature-request 🙁
