### ISSUE TITLE
firebase-app-distribution app_path resolved incorrectly

### ISSUE THREAD

**Issue by viktorasl** [bitrise-io/bitrise-steplib#3108]
https://github.com/bitrise-io/bitrise-steplib/blob/f14d8a376551e2c7be19bfc09883a2dba1891171/steps/firebase-app-distribution/0.9.0/step.yml#L45

If i.e `BITRISE_IPA_PATH` is defined then this line produces:
```
app_path: /path/to/ipa||
```

and then next step that uses the `app_path` fails, because it contains two column characters at the end. Previous version `0.8.0` had one one column character at the end and somehow it did not bother other steps.

/cc @guness

I tried fixing it in steplib but could not find a way to inject some sort of script to resolve it as it was intended. Probably the best way is to do three separate variables and resolve in the step source.

**Comment by guness** [comment]
Good catch, and sorry for the trouble. You can continue using v0.8.0 until this is fixed. I will check this asap.

**Comment by guness** [comment]
should be fixed by #3111

**Comment by guness** [comment]
@viktorasl can we close the issue now?
_or someone else_
