### ISSUE TITLE
virtual-device-testing-for-android provides no log when a test fails

### ISSUE THREAD

**Issue by danielesegato** [bitrise-io/bitrise-steplib#3191]
Is there a flag to enable in configuration of the step to enable logging?

all we got was a rather unhelpful

```
Waiting for test results
- Validating
- (1/1) running
- (0/1) running
=> Test finished

Test results:
Model    API Level   Locale   Orientation   Outcome              
Pixel2   29          it       portrait      failure   
```

would be nice to have at least which test failed, even better the full log

**Comment by shams-ahmed** [comment]
I’m closing this issue because it has been inactive for more than a week. This probably means that it is not reproducible or it has been fixed in a newer version.

Thank you!
