### ISSUE TITLE
[transfer ownership] Nowsecure Auto Analysis

### ISSUE THREAD

**Issue by sp3nx0r** [bitrise-io/bitrise-steplib#3343]
We're transferring ownership of community written https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/bitrise-step-nowsecure-auto-analysis to be maintained by the vendor themselves. Any special magic necessary in order to make that transfer as we submit a new version of the step?

**Comment by sp3nx0r** [comment]
That's what I thought, I'd mentioned that to them. Dropped them a link to this issue and someone from their product team should respond here to wrap this up. Didn't want to volunteer anyone. Cheers

**Comment by TcohnNS** [comment]
@sp3nx0r sorry for the delay, we had some confusion around this. 
Our legal team  reviewed and approved the contract , so the the step should be republished by EOW. 

Thank you for your patience.. 
Tammy (PM@ NS)
