### ISSUE TITLE
Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 193

### ISSUE THREAD

**Issue by JustasM11** [bitrise-io/bitrise-steplib#3344]
INFO[19:16:41] Start installing (curl) with apt-get         
+------------------------------------------------------------------------------+

| (6) telegram-notify@1                                                        |
+------------------------------------------------------------------------------+
| id: telegram-notify                                                          |
| version: 1.0.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-01-11T19:16:41Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[19:16:41]  * [OK] Step dependency (curl) installed, available. 
+ MESSAGE='🛑 *profession-c-plus-plus*: build 37 failed 😕 \nURL: https://app.bitrise.io/app/3a3204a3b62de311\nCommit: Adding correct coverage.txt
 \n\n Branch: adding_coverage
Commit hash: def7dd01d655d6698bc6bba3ec1824d4561f0e5b
Commit subject: Adding correct coverage.txt
Commit message: '
+ '[' 0 -eq 0 ']'
+ MESSAGE='✅ *profession-c-plus-plus*: build 37 passed! 🎉\nCommit: Adding correct coverage.txt
\n Download URL ⬇️: https://app.bitrise.io/build/204b4841-c214-4160-ac10-bb814ac80702\n\n Branch: adding_coverage
Commit hash: def7dd01d655d6698bc6bba3ec1824d4561f0e5b
Commit subject: Adding correct coverage.txt
Commit message: '
+ curl -X POST -H 'Content-Type: application/json' -d '{ "chat_id": "[REDACTED]", "text":"✅ *profession-c-plus-plus*: build 37 passed! 🎉\nCommit: Adding correct coverage.txt
\n Download URL ⬇️: https://app.bitrise.io/build/204b4841-c214-4160-ac10-bb814ac80702\n\n Branch: adding_coverage
Commit hash: def7dd01d655d6698bc6bba3ec1824d4561f0e5b
Commit subject: Adding correct coverage.txt
Commit message: ", "parse_mode": "markdown" }' https://api.telegram.org/bot[REDACTED]/sendMessage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   522  100   137  100   385    424   1191 --:--:-- --:--:-- --:--:--  1611
{"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 193"}|  

![image](https://user-images.githubusercontent.com/12593214/149007676-a885d1c9-c0d9-4eeb-a78a-55b3c8972552.png)

**Comment by ofalvai** [comment]
Hey @JustasM11, the Telegram step is not maintained by us, please file a bug report in its own repo: https://github.com/mcaldas/bitrise-step-telegram-notify

**Comment by JustasM11** [comment]
ok
