### ISSUE TITLE
generate-changelog go error

### ISSUE THREAD

**Issue by jugbeep** [bitrise-io/bitrise-steplib#3597]
I'm seeing this issue:

+------------------------------------------------------------------------------+

| (13) generate-changelog@0                                                    |
+------------------------------------------------------------------------------+
| id: generate-changelog                                                       |
| version: 0.10.0                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2022-08-30T20:41:40Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
# github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
src/github.com/bitrise-steplib/steps-generate-changelog/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:121:3: too many errors
ERRO[20:41:41] Step (generate-changelog@0) failed: Failed to prepare the step for execution through the required toolkit (go), error: Failed to install package, error: command `/usr/local/bin/go "build" "-o" "/Users/vagrant/.bitrise/toolkits/go/cache/https___github.com_bitrise-io_bitrise-steplib.git-generate-changelog-0" "github.com/bitrise-steplib/steps-generate-changelog"` failed: exit status 2 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | generate-changelog@0 (exit code: 1)                           | 3.82 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...github.com/bitrise-steplib/steps-generate-changelog/issues |
| Source: https://github.com/bitrise-steplib/steps-generate-changelog          |
+---+---------------------------------------------------------------+----------+

**Comment by lpusok** [comment]
Sorry for the breakage, please update to the latest version: https://github.com/bitrise-steplib/steps-generate-changelog/releases/tag/0.10.1.
Issue was caused by the golang 1.18 update.
