### ISSUE TITLE
apt-get-install error The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>

### ISSUE THREAD

**Issue by hosseintalebi** [bitrise-io/bitrise-steplib#3720]
The `apt-get-install` step is giving us this error on `Ubuntu 20.04 Elite` machines:
```
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```
The issue seems to be related to:
> the "apt-key add" method is deprecated in newer Debian-based distributions and will result in ugly warnings when you run "apt-get update". 
[Source](https://github.com/yarnpkg/yarn/issues/7866#issuecomment-1403268001).

**Comment by hosseintalebi** [comment]
In a support ticket, bitrise team said that they are working on a fix. In the meantime running this script before the failing step should help:
```
sudo apt-key adv --keyserver hkps://[keyserver.ubuntu.com](http://keyserver.ubuntu.com/) --refresh-keys
```

**Comment by jbedard-coveo** [comment]
```
sudo apt-key adv --keyserver hkps://[keyserver.ubuntu.com](http://keyserver.ubuntu.com/) --refresh-keys
bash: syntax error near unexpected token `('
```
