### ISSUE TITLE
Gemfile.lock files causes failure

### ISSUE THREAD

**Issue by Reedyuk** [bitrise-io/bitrise-steplib#521]
Hi,
I had a gemfile.lock in my root of my project, this caused the cocoapods install to fail, i assume its because you look for any .lock file in the step.
After i removed the gemfile.lock then it worked fine.

**Comment by viktorbenei** [comment]
Without the log hard to say, but yes, the step searches for Gemfile(.lock) in the repo and if you have one it expects that you defined the CocoaPods version you want to use in that.

P.S.: please if you create a GitHub issue create it in the repo of the step, and not in this one, which is the step library / collection.
