### ISSUE TITLE
Android SDK on OSX?

### ISSUE THREAD

**Issue by Almouro** [bitrise-io/bitrise-steplib#551]
Hi guys!

Not sure if this is the right place to post this issue... My apologies if it's not :(

At @bamlab, we use Bitrise for our React Native projects, and we like to build both Android and iOS versions of the project on the same stack. 
For now, we made a custom step installing Android SDK with Brew via a script, and adding the required tools.

Do you think it would be a good idea to include the Android SDK on the OSX stacks? If so, should we make a PR on https://github.com/bitrise-io/osx-box-bootstrap?
Or do you think it'd be best to submit an Android SDK step for the OS stacks?

Thanks! :)

**Comment by viktorbenei** [comment]
Hi,

Could you please move this question to https://github.com/bitrise-io/bitrise.io ? We'll reply there, as that's where others can join the discussion.
Thanks!

**Comment by Almouro** [comment]
Sure! Moved to [here](https://github.com/bitrise-io/bitrise.io/issues/45)

**Comment by viktorbenei** [comment]
Thanks! 😊
