### ISSUE TITLE
Feature request: Add a step for integrating with AWS device farm

### ISSUE THREAD

**Issue by EPICAPPSLTD** [bitrise-io/bitrise-steplib#578]
In order to extend test coverage to multiple real devices it would be nice if you could add a step for integrating with AWS Device Farms, the step wouldn't need to wait until the device farm has finished all tests (as the process for waiting for devices can be very slow), but knowing that it can trigger a device farm deployment would provide development team with very valuable test information.

Here's the link for AWS Device Farms: 
https://aws.amazon.com/device-farm/

**Comment by viktorbenei** [comment]
Please if you want to submit a feature request do it on UserVoice or in this GitHub repository: https://github.com/bitrise-io/bitrise.io

We do not track issues here, this is just a step lib / collection repo (~ auto generated).
