### ISSUE TITLE
Allow or not a step to run in PR mode

### ISSUE THREAD

**Issue by dagio** [bitrise-io/bitrise-steplib#731]
What's the proper way to let the user choose to run a step or not in PR mode ? A regular step input ?

**Comment by viktorbenei** [comment]
`run_if: .IsPR`

**Comment by viktorbenei** [comment]
but I guess an input would also work, `run_if` is a generic concept, an input is more of a step's own way

**Comment by viktorbenei** [comment]
ohh, and of course `run_if` is built in, so you don't have to do anything to support it, if you use an input then you'll have to implement the functionality in your step

**Comment by viktorbenei** [comment]
example - cache:push by default only runs in CI mode and if it's **not** PR mode -> https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/cache-push/0.9.3/step.yml#L33
