### ISSUE TITLE
How does one add an icon to a step?

### ISSUE THREAD

**Issue by nhammond101** [bitrise-io/bitrise-steplib#774]
My apologies if this is in the docs somewhere, but how does a step contributor add an icon to their steps?

**Comment by viktorbenei** [comment]
No problem, I think we don't have it in the docs.

Just create a new pull request, adding the icon SVG into `steps/YOUR-STEP-ID/assets/icon.svg`. See https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/amazon-s3-upload (or any other step which has an icon) for an example of the dir structure.

**Comment by nhammond101** [comment]
nice one, thanks for the update
