### ISSUE TITLE
Create step for setting GH commit status to 'pending'

### ISSUE THREAD

**Issue by tomburns** [bitrise-io/bitrise-steplib#861]
I'm currently using the GitHub status step to set the commit status of my PRs on our Github Enterprise repos when the builds finish. Could we get a second step for running at the beginning of these builds which simply does the same thing but sets the status to *pending*?

**Comment by godrei** [comment]
Hi @tomburns ,
i shared a new version ([1.0.1](https://github.com/bitrise-steplib/steps-github-status/releases/tag/1.0.1)) of Github Status step.

Thanks for the feature!
